### ISSUE TITLE
add windows specific install instructions, may need Microsoft C++ installed

### ISSUE THREAD

**Issue by theresekoch** [NickleDave/vak#262] opened 2020-11-23 23:28 UTC
## System Specs
Windows 10 Home Version 1909

## Reproduction

1. install latest version of conda
2. create and activate new conda environment
3. ran `conda install vak -c nickledave`
4. Here is the error I get: 

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - vak

Current channels:

  - https://conda.anaconda.org/nickledave/win-64
  - https://conda.anaconda.org/nickledave/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page

**Comment by NickleDave** [comment] 2020-11-23 23:37
Hi @theresekoch thank you for the detailed issue report.

🤔 I think that must mean I don't have a windows version built -- sorry about that!

I know this is not quite as convenient, but could you please try installing from source as described here?
https://vak.readthedocs.io/en/latest/get_started/installation.html#from-source-e-g-for-development

**Comment by theresekoch** [comment] 2020-11-24 00:27
No trouble at all! I went ahead and installed it using pip. I had to install pytorch separately, but now it seems to all be working fine. The one hiccup I ran into with pip install seems to stem from the fact that pytorch on windows requires Microsoft visual C++, which I didn't have and which didn't install automatically. That might be more of a pytorch issue, but just in case other people on windows run into a similar problem, that solved it.

**Comment by NickleDave** [comment] 2020-11-24 15:40
Thank you @theresekoch that's helpful to know!

Just to clarify:  
you ran `pip install torch` to add it to a `conda` environment, but when you tried to import it you got some error like  
```
>>> import torch       
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.  
It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe                                 
Traceback (most recent call last):                                                                                       
 File "<stdin>", line 1, in <module>                                                                                     
File "C:\Users\aliag\anaconda3\envs\pytorchPractice\lib\site-packages\torch\__init__.py", line 127, in <module>           
raise err                                                                                                           
OSError: [WinError 126] 指定されたモジュールが見つかりません。 
Error loading "C:\Users\aliag\anaconda3\envs\pytorchPractice\lib\site-packages\torch\lib\asmjit.dll" 
or one of its dependencies. 
```
(from https://stackoverflow.com/questions/63212096/when-importing-pytorch-microsoft-visual-c-redistributable-is-not-installed)

The torch docs for install with pip on Wheel suggest downloading a wheel, like this:  
`pip install torch===1.7.0 torchvision===0.8.1 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`
Not super intuitive but I think it's because their build is very complex?

If I've got that right, I will raise a separate issue to add that to the documentation

**Comment by theresekoch** [comment] 2020-11-24 17:13
I actually used `conda install pytorch torchvision torchaudio cpuonly -c pytorch` to install pytorch in a conda environment, but that is the error message that came up. The error message was easy enough to follow (downloaded the Microsoft Visual C++ from the link in the error message), so maybe that's still easier than the wheel? Maybe just adding to the docs that people on windows might have to install Microsoft Visual C++ first would be the most straightforward.

**Comment by NickleDave** [comment] 2020-11-25 16:04
I see, thank you.
Changing the issue title to reflect that

**Comment by NickleDave** [comment] 2022-01-08 20:14
Hi @theresekoch thank you again for raising this issue.

I want to let you know I have put `vak` on `conda-forge` and I have updated the install instructions:  
https://vak.readthedocs.io/en/latest/get_started/installation.html#with-conda

I did test on a Windows machine, and found that I was able to create a new environment with `vak` installed, without any extra steps, by doing:  
```console
conda create -n vak-env vak -c conda-forge -c pytorch
```

If you are still using `vak` and could test for me whether this resolves your issue, it would be much appreciated!
(and I'll add you as a contributor for docs + bugs, which will give you open source bragging rights :smile: )

**Comment by theresekoch** [comment] 2022-01-10 17:54
Hi @NickleDave , thanks for the update! I am still using `vak` and always happy to help out! I am now working on a machine running Windows 11 Home version 21H2. Using conda 4.11.0, I ran `conda create -n vak-env vak -c conda-forge -c pytorch`  in a fresh virtual environment, and it ran just fine with no errors. 

In a python session in `vak-env`, I am able to import vak and it seems to be working, but the command line interface is not. If I run `vak --help` from the command prompt in the `vak-env` environment, I get the message: 
```
'vak' is not recognized as an internal or external command,
operable program or batch file.
```
Maybe something wasn't added to my PATH correctly? Or windows isn't recognizing something as an executable? If you have any suggestions for how to correct them I'm happy to try them out and let you know how it goes. I personally don't use the command line interface with `vak` (I use the python package), so it's not a huge issue for me, but it would make the install challenging for someone hoping to use the command line interface as described in the docs.

**Comment by NickleDave** [comment] 2022-01-10 23:56
Thank you @theresekoch, that is super helpful.

(Also glad to hear you are still using `vak` :slightly_smiling_face: )

I did not think to check the cli -- good idea.  And I appreciate your offer to test, but I'm wondering if there's something I needed to do when I made the "recipe" for conda-forge.

Let me do the detective work on that before I ask you to test. Much appreciated though! :pray: 
Going to leave this open for now

**Comment by NickleDave** [comment] 2022-01-10 23:57
@all-contributors please add @theresekoch for docs bugs

**Comment by NickleDave** [comment] 2022-01-11 00:10
confirming I can reproduce this bug on Windows ☹️ even though I *can* run `vak --help` on Ubuntu in a `conda` env where I installed from `conda-forge`

**Comment by NickleDave** [comment] 2022-01-12 01:52
update: I got some feedback from the conda-forge gitter.
Seems like I left out an `entry_points` option in the `build` section of the `meta.yaml` recipe

I'm going to try and update the recipe with that added -- @theresekoch may ask you to test again once the update gets built

**Comment by NickleDave** [comment] 2022-01-12 03:10
In theory this PR should have fixed it:
https://github.com/conda-forge/vak-feedstock/pull/1

I think we need to wait for the conda-forge infra to rebuild though?
Will check again tomorrow

**Comment by NickleDave** [comment] 2022-01-12 13:02
@theresekoch it seems like I am now able to do
```
conda create -n vak-forge-test vak -c conda-forge -c pytorch
```
on windows and then
```
(vak-forge-test) C:\Users\Nickl>vak -h
usage: vak [-h] command configfile

vak command-line interface

positional arguments:
  command     Command to run, valid options are:
              ('prep', 'train', 'eval', 'predict', 'learncurve')
              $ vak train ./configs/config_2018-12-17.toml
  configfile  name of config.toml file to use
              $ vak train ./configs/config_2018-12-17.toml

optional arguments:
  -h, --help  show this help message and exit
```

(as you suggested) to confirm the cli actually works too

could you please confirm that it's not just me? 🙏

**Comment by theresekoch** [comment] 2022-01-12 15:44
This also works for me now! Thanks again for the updates!

**Comment by NickleDave** [comment] 2022-01-13 00:30
Awesome! Thank you for checking!

I am calling this closed by https://github.com/conda-forge/vak-feedstock/pull/1 then

**Closed by NickleDave** 2022-01-13 00:30 UTC
Labels: DOC: documentation

**Comment by NickleDave** [comment] 2022-01-15 19:54
Thank you! It would definitely be good to compare notes, I'll send you an email
