### ISSUE TITLE
vak.util.dataset.has_unlabeled raises error when dataset has a single annotation file

### ISSUE THREAD

**Issue by yardencsGitHub** [NickleDave/vak#101] opened 2020-03-05 18:53 UTC
vak prep worked in the 'add-labels-from-df' branch.

Does the .csv file constitute the only output?
(and some updates to the .toml file)

In the .csv file I’m not sure what the ‘duration’ fileld point to but the timebin_dur rounds the actual number. I hope that is not important but if this number is later used to calculate time points in files it is going to lead to errors.

I tried to running vak train. Got some issues that required commenting out parts of the .toml file. 
Got an error message very similar to issue 99:

 File "c:\users\yarden cohen\repos\vak\src\vak\util\dataset.py", line 48, in has_unlabeled
 lbls_int = [tmp_labelmap[lbl] for lbl in annot.seq.labels]
AttributeError: 'list' object has no attribute 'seq'

**Comment by NickleDave** [comment] 2020-03-07 14:32
Ok, thank you, I will merge in the 'add-labels-from-df' branch.
We need to add a unit test to make sure this bug stays fixed, I will raise an issue for that.

I think the bug you found can be fixed with the same utility function I added.
Btw, you can reference previous issues with a "#" like so:
"this error seems to be the same as #99" 

There's a couple of other concerns you brought up, like the rounded duration in the dataset files.
Can you please raise a separate issue about that?
It is important but we'll never track it if it's hidden in some other issue about a bug.
Let's try to only raise one problem per issue, and clearly state it in the title.

**Comment by NickleDave** [comment] 2020-03-07 17:55
started fixing this:
https://github.com/NickleDave/vak/tree/fix-has-unlabeled-single-annot-file-%23101

@yardencsGitHub can you test this fix "manually" for me?

**Comment by yardencsGitHub** [comment] 2020-03-09 18:12
Switched to the new branch and ran vak train. (not vak prep again)
The previous issue (like #99) did not occur but the run did not complete.. 

(tweetyenv_alpha) D:\YardenBirds\llb3_spring>vak train config-llb3-04232019.toml
Logging results to D:\YardenBirds\llb3_spring\results\results_200309_140219
Size of each timebin in spectrogram, in seconds: 0.003
using training dataset from D:\YardenBirds\llb3_spring\train\annotated_prep_200305_122100.csv
Traceback (most recent call last):
  File "C:\Anaconda3\envs\tweetyenv_alpha\Scripts\vak-script.py", line 11, in <module>
    load_entry_point('vak', 'console_scripts', 'vak')()
  File "c:\users\yarden cohen\repos\vak\src\vak\__main__.py", line 43, in main
    config_file=args.configfile)
  File "c:\users\yarden cohen\repos\vak\src\vak\cli\cli.py", line 21, in cli
    train(toml_path=config_file)
  File "c:\users\yarden cohen\repos\vak\src\vak\cli\train.py", line 114, in train
    [transforms.Lambda(standardize),
  File "C:\Anaconda3\envs\tweetyenv_alpha\lib\site-packages\torchvision\transforms\transforms.py", line 318, in __init__
    assert callable(lambd), repr(type(lambd).__name__) + " object is not callable"
AssertionError: 'NoneType' object is not callable

**Comment by NickleDave** [comment] 2020-03-14 14:05
@yardencsGitHub will work on fixing this now
I think what's happening is that you have normalization set to None and it's trying to apply that as a transform anyway--i.e., I failed to put in logic to handle "no normalization"

**Comment by NickleDave** [comment] 2020-03-14 15:27
@yardencsGitHub I am having trouble testing whether the fix for the bug in this issue works, related to the versions of your datasets I have. 

I think I have a hacky way around it, but I'm raising an issue on the paper repository, because this impacts whether we can re-use models / reproduce our own results

**Comment by NickleDave** [comment] 2020-03-14 19:22
fixed by #107

**Closed by NickleDave** 2020-03-14 19:22 UTC
